### ISSUE TITLE
Syntax highlighting for directives like code and raw

### ISSUE THREAD

**Issue by nebbles** [vscode-restructuredtext/vscode-restructuredtext#142]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 99.0.0
- [x] Visual Studio Code version: 1.30.2
- [x] Operating System version: macOS 10.14.2
- [x] Python version: 2.7.15 / 3.7.0
- [x] sphinx version: 1.8.2
- [x] A sample of conf.py or its important fragments: Nothing special

**Expected behavior**

In Atom, syntax highlighting works as expected:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/12599555/52015010-e5e47000-24d8-11e9-9ed1-54666f07c27d.png">

**Actual behavior**

From VSCode as you can see the syntax highlighting is sparse in comparison:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/12599555/52014952-c5b4b100-24d8-11e9-9a73-7780bc4c2937.png">

Note that the error for `.. code::` is `[restructuredtext] D000 Error in "code" directive:`

**Detailed Steps to reproduce the problem**

I guess in part there is some connection with #58 and #137...

I'm wondering why this is? Any chance this could be fixed or added as an improvement? I'd love to help contribute but this stuff flies over my head.

**Comment by lextm** [comment]
Because Atom and VSCode have different engines for that, it is not clear if there is an easy way to achieve the same. Will need some investigation.

**Comment by SamB** [comment]
This is probably the grammar Atom is using: https://github.com/Lukasa/language-restructuredtext/blob/master/grammars/restructuredtext.cson

It appears to basically be a textmate grammar in [yet another user-friendly JSON varient (CSON)](https://github.com/bevry/cson), with metadata that somehow wires it up to the files automatically? And atom can apparently load cson directly (no build step is in evidence); sure would be nice if vscode could do that.

So, since this is a textmate grammar, not a treesitter one, it could really be just a matter of stealing that grammar and using it instead of the existing one, which looks pretty much as though it's been pulled straight from the textmate bundle? (Granted, one XML plist looks much like another ... there *might* be information in there *somewhere*, but who can tell?)

**Comment by rmorshea** [comment]
Since it seems like this issue has remained for a long time, I'd suggest implementing #210. Obviously it would be nice to get this highlighting to work at some point, but being able to disable highlighting entirely would alleviate readability issues in the interim.

**Comment by lextm** [comment]
The test code is
```
This is a title
===============

This is a **bold** paragraph.

.. image:: _static/my_image.png
  :width: 70%
  :align: center

.. code:: python

   def foo():
     return 4
   
   bar = foo()
   print(bar)

.. raw:: html

  <div style="text-align:center">
  <a class="btn btn-info btn-custom" href="google.com" role="button"
  style="margin-bottom:20px;white-space:normal;">Press me!</a>
  </div>
```

In release 154.0.0 the old grammar file was replaced by the one from https://github.com/trond-snekvik/vscode-rst .

Close this item now as it does not appear with that grammar file.
