### ISSUE TITLE
'command not found' after update to 108.0.0

### ISSUE THREAD

**Issue by panigrc** [vscode-restructuredtext/vscode-restructuredtext#156]
**Environment**
- [x] Extension version: 108.0.0
- [x] Visual Studio Code version: 1.33.1
- [x] Operating System version: Windows 7 Sp1 x64
- [x] Python version: 2.7.14
- [x] sphinx version: 1.6.6
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

I should see the preview when I click on the Preview icon.

**Actual behavior**

I get a notification:
`command 'restructuredtext.showPreviewToSide' not found`

**Detailed Steps to reproduce the problem**

Updated from 107.0.0

**Comment by lextm** [comment]
I could not reproduce this on a Mac and a Windows machine.

Can you try the following?

1. Remove the extension and reload.
1. Close VSCode and reopen.
1. Install this extension once again.

**Comment by panigrc** [comment]
I close the issue cause I didn't find any solution.
I switched back to version 105.0.0 which works fine.
If a new version is out I'll try again.

**Comment by slaneyrw** [comment]
I get this after updating to either v107 or v108.  Reverting back to v106 was the last version that worked.

**Comment by lextm** [comment]
A test build is added,

[restructuredtext-108.0.0.vsix.zip](https://github.com/vscode-restructuredtext/vscode-restructuredtext/files/3189772/restructuredtext-108.0.0.vsix.zip)

**Comment by lextm** [comment]
Release 109.0.0 is just released. This issue is fixed.

**Comment by Zyxon123** [comment]
Same thing happening here after new VS Code update. 

**Environment**

- [x]   Extension version: 109.0.0
- [x]   Visual Studio Code version: 1.35.0
- [x]   Operating System version: Windows 10 x64

**Expected behavior**

I should see the preview when I click on the Preview icon.

**Actual behavior**

I get a notification:
command 'restructuredtext.showPreviewToSide' not found

**Detailed Steps to reproduce the problem**

Update VS code to latest version and click the Preview button.

**Comment by lextm** [comment]
@Zyxon123 Another possible cause has been identified and fixed in release 110.0.0. Can you update and try again?

If the issue remains, you can use Developer Tools to see what's recorded in the Console,

https://docs.restructuredtext.net/articles/troubleshooting.html#use-developer-tools
