### ISSUE TITLE
The preview engine selection might be made a separate setting

### ISSUE THREAD

**Issue by lextm** [vscode-restructuredtext/vscode-restructuredtext#177]
The setting `restructuredtext.confPath` today is used for two purposes,

* When it is empty (`""`), it means docutil engine should be used.
* When it is a valid path, it means sphinx engine should be used, as well as indicates the conf file sphinx should use.

This design led to a limitation that preview engine selection cannot be made per user.

If you like the engine selection to be a separate setting, please vote it up.

**Comment by Yajo** [comment]
In the best case (that you're right and this setting must be in the project config), the method this extension uses is most annoying because of this single thing: it adds the setting to a git-controlled file automatically.

*All* other settings in *all* other extensions can reside either in the user settings or the project settings (project settings override user settings always, if present), and *all* of them save automatically *only* the user settings. Modifying this behavior would make the extension work more as expected for a vscode user.

Modifying `.vscode/settings.json` must be a conscious work, done explicitly by a dev that knows what he's doing and that it will affect other collaborators.

If a PR comes in and you see that this file is being modified because of an editor extension, that's disgusting... At least that's how I felt when it happened to me. :man_shrugging:

**Comment by lextm** [comment]
* "all of them save automatically only the user settings" is a false statement. As far as I know the Python extension from Microsoft does save settings to project level.
* Besides, many projects don't even save .vscode folder in Git.

So, your specific preference of using VSCode is not something universal, and that's why it requires significant amount of votes from the current user base (~100,000 installs now).

**Comment by Yajo** [comment]
Somebody today reached me about this subject again. He (like me) just wanted syntax highlighting and doesn't care about the engine to render rst files.

I just wanted to mention here the only possible workaround I found, to try to help somebody else out there who gets hit by this bug: **uninstall the extension**.

**Comment by lextm** [comment]
@Yajo you tried to help in the wrong way. Starting from release 129.0.0, by disabling the preview engines you get what you want, https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/216#issuecomment-657275073
