### ISSUE TITLE
Getting a warning for doc8 despite setting "restructuredtext.linter.disabled": true

### ISSUE THREAD

**Issue by segevfiner** [vscode-restructuredtext/vscode-restructuredtext#181]
**Environment**
- Extension version: 115.0.0
- Visual Studio Code version: 1.40.0
- Operating System version: Windows 10.0.18362.418 x64
- Python version: 3.8.0 x64

**Expected behavior**
I should not be getting an error for doc8 if I have set `"restructuredtext.linter.disabled": true` as it should not be run then.

**Actual behavior**
I'm getting the following error:
```
python.exe: Error while finding module specification for 'doc8.main' (ModuleNotFoundError: No module named 'doc8')
```

**Detailed Steps to reproduce the problem**
1. Enable `"restructuredtext.linter.disabled": true` (User level).
2. Open any rst file.

**Comment by lextm** [comment]
For release 115.0.0 you need to set `restructuredtext.linter.run` to `off`,

https://docs.restructuredtext.net/articles/configuration.html#lint-ontype-or-onsave-or-not-at-all

I am working on a new release so that `restructuredtext.linter.disabled` can take precedence.

**Comment by datalifenyc** [comment]
If you have the doc8 module installed and are receiving the following error: `ModuleNotFoundError: No module named 'doc8'`, it is likely due to the doc8 executable path being in a different location than the extension's default setting. My VSC environment was Anaconda (Python 3.7.4), but the rST extension was looking for the doc8 executable in my 2.7 path (MacOS Catalina). So, I had to set the `Restructuredtext > Linter: Executable Path` to the anaconda3/bin folder. Then the message went away.

1. Click on the gear icon for the reStructuredText extension.
2. Select **Configure Extension Settings**
3. Go to `Restructuredtext > Linter: Executable Path`
4. Enter `/Users/user_name/anaconda3/bin` [MacOS]

**Note:** Windows path will be different. Locate the bin folder that contains the doc8 executable.
