### ISSUE TITLE
No preview. Preview engine sphinx is disabled.

### ISSUE THREAD

**Issue by LiuhaosGitHub** [vscode-restructuredtext/vscode-restructuredtext#209]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version:
- [ ] Visual Studio Code version:
- [ ] Operating System version:
- [ ] Python version:
- [ ] sphinx version:
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

**Actual behavior**

**Detailed Steps to reproduce the problem**

**Comment by LiuhaosGitHub** [comment]
No preview. Preview engine sphinx is disabled.

**Comment by lextm** [comment]
This is by design. The extension at startup asked you whether to install Sphinx as preview engine, and you refused,

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/125.0.0/src/python.ts#L83

To address it, install Sphinx and also change the setting of `restructuredtext.preview.sphinx.disabled` to `false`.

**Comment by ddl-lgaddie** [comment]
FYI, I still get this issue even though Sphinx is installed and I've configured the Sphinx Build Path with the absolute path (`/usr/local/opt/sphinx-doc/bin/sphinx-build`).

**Comment by lextm** [comment]
@ddl-lgaddie Please open a new issue and provide more details (such as the log written by this extension). Thanks.
