### ISSUE TITLE
[Feature]: refresh preview when dependencies change

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#326]
### Is your feature request related to a problem? Please describe.

The preview does not update when I modify files that a .rst file depends on.

Examples of such files are: images, a text file included using "literalinclude", or a .yaml file used by "datatemplate" directive, a file that is rendered by the plantuml directive, etc.

### Describe the solution you'd like

Modifying a dependency should re-render the preview.

### Describe alternatives you've considered

Make a dummy change to the .rst file, save, then undo and save again.

**Comment by lextm** [comment]
After switching to esbonio, this issue is partially resolved, because this language server monitors the changes of the project and recompile when needed. The live preview is updated every time a build succeeds.

Even if esbonio fails to recompile the project, in release 176.0.0 and above users can click the "esbonio: xxx" area in status bar to force restart the language server, which in turn triggers recompilation and preview refresh.
