### ISSUE TITLE
[Bug]: Preview silently stopped working in v173.0.0; workaround downgrade to v172.0.0 

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#351]
### Expected behavior

Preview has worked fine. I make a change, I save, I saw the preview

### Actual behavior

When I make a change and save, I see only this in the log:

```
[deleted]
[Log - 11:49:12 AM] [preview] Sphinx conf.py directory: [deleted]/docs/workflow
[Log - 11:49:12 AM] [preview] Sphinx html directory: [deleted]/_build/html
[Log - 11:49:12 AM] [preview] Working directory: [deleted]/workflow
[Log - 11:49:12 AM] [preview] HTML file: [deleted]/_build/html/working/index.html
[nothing after this]
```

The preview shows only:

```
Cannot show preview page.
Description:
Cannot read preview page "[deleted]]/_build/html/working/index.html".

Possible causes are,

A wrong "conf.py" file is selected.
Wrong value is set on "restructuredtext.builtDocumentationPath".
Detailed error message
Error
ENOENT: no such file or directory, open '[deleted]]/_build/html/working/index.html'
Error: ENOENT: no such file or directory, open '[deleted]]/_build/html/working/index.html'
More Information
Diagnostics information has been written to OUTPUT | reStructuredText panel.

The troubleshooting guide can be found at

https://docs.restructuredtext.net/articles/troubleshooting.html
```

### Detailed steps

```
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:43:02.136Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-28-generic
```

### Extension information

v173.0.0

### Visual Studio Code information

1.60.0

### Operating system information

Ubuntu 21

### Python information

3.9.7

### Sphinx information

4.4.0

### Contents of conf.py

```python
Same result even with an empty conf.py
```

**Comment by lextm** [comment]
The meaning of `restructuredtext.builtDocumentationPath` has changed in release 173.0.0.

If in the past you set it to `xxxx/_build/html`, then after upgrading to release 173.0.0 you need to change it to `xxxx/_build`.

**Comment by oharboe** [comment]
> The meaning of `restructuredtext.builtDocumentationPath` has changed in release 173.0.0.
> 
> If in the past you set it to `xxxx/_build/html`, then after upgrading to release 173.0.0 you need to change it to `xxxx/_build`.
> 
> This setting will be removed in the coming releases to avoid confusion.

I've tried setting it to both values below, neither work:

```
    "restructuredtext.builtDocumentationPath": "${workspaceFolder}/_build",
```

and

```
    "restructuredtext.builtDocumentationPath": "${workspaceFolder}/_build/html",
```

**Comment by lextm** [comment]
So, you are working with virtualenv. Can you install esbonio first? Then before each time you activate the live preview, check if "esbonio: idle" is there in the status bar and no error in Esbonio Language Client logging.

**Comment by rainerth** [comment]
I have the same issue here. On 3 separate installations (1 x Linux after regular update, 1 x Windows 10 after regular update, 1 x Windows 10 with a fresh installation). I went back from v173 to v172 to v171 to v170. The first version with a working preview was v170.

**Comment by oharboe** [comment]
@rainerth Try rebooting. I will on Monday. There can be lingering processes when upgrading that are not compatible with the upgraded plugin.

**Comment by rsokl** [comment]
I also had to downgrade to v170 to fix this

**Comment by lextm** [comment]
@rainerth If you are going to test again on Monday, please try to use release 174.0.0 which contains better error logging around esbonio language server,

1. Old `restructuredtext.xxx` settings around live preview are automatically migrated to `esbonio.xxx` settings so that the language server can pick them up directly and monitor their changes.
2. The status bar for esbonio has more states to reflect its runtime status (especially when the project failed to build). Its label always says `esbonio: NNN`.
3. The logging channel is `Esbonio Language Server` under VSCode `OUTPUT`, so you can find more about whether esbonio detects any error with your project/files which prevents live preview from working.

**Comment by lextm** [comment]
@rainerth @rsokl Please try release 174.0.0. If any error remains on your machine, please open new issues. The switch from snooty to esbonio is huge, so I expect quite a few projects to experience similar issues but the causes can vary. By keeping each reports in a single issue we can better track them and handle them one by one.

**Comment by oharboe** [comment]
> @oharboe If you are going to test again on Monday, please try to use release 174.0.0 which contains better error logging around esbonio language server,
> 
> 1. Old `restructuredtext.xxx` settings around live preview are automatically migrated to `esbonio.xxx` settings so that the language server can pick them up directly and monitor their changes.

Aha! We have a script that sets up vscode. It has the old settings, so there's a chance that automigration isn't run!

For example:

1. I upgrade the plugin, the settings are migrated to esbonio
2. Run script to set up vscode project settings
3. The settings are migrated

I have modified our centralized settings so they now include the new esbonio settings. Let's see what that does.

**Comment by lextm** [comment]
@oharboe That sounds not good to me. So, some background below for release 174.0.0.

The new `esbonio.xxx` settings do not support macros like `workspaceFolder` (but `restructured text.xxx` settings do expand the macros), so if your script sets their values with any macro then things might break.

To avoid breaking changes to most users, the migration of settings is just partially implemented so that,

* All current settings of `restructuredtext.xxx` are preserved.
* During extension startup, the values of `restructuredtext.xxx` are written to `esbonio.xxx` (macros are expanded) so that the language server can pick them up.

Therefore, when you test release 174.0.0, you might keep all your settings on `restructuredtext.xxx` and avoid changing `esbonio.xxx` manually (so that they can automatically overwritten by the extension).

**Comment by oharboe** [comment]
> @oharboe That sounds not good to me. So, some background below for release 174.0.0.
> 
> The new `esbonio.xxx` settings do not support macros like `workspaceFolder` (but `restructured text.xxx` settings do expand the macros), so if your script sets their values with any macro then things might break.

That's going to cause a lot of confusion for sure....

**Comment by lextm** [comment]
Plan to close this issue soon, so please test if it still remains on your side with the new release 176.0.0.

**Comment by oharboe** [comment]
We have found out what the problem was here, so I am good to close and file new github issue if something arises.
