### ISSUE TITLE
[Bug]: esbonio does full build on restart

### ISSUE THREAD

**Issue by twodrops** [vscode-restructuredtext/vscode-restructuredtext#378]
### Expected behavior

esbonia shall use the incremental build of sphinx (doctree cache) and builds only changed files on restart of language server or vscode.

### Actual behavior

Always does full build. For our project where the build lasts 4-5 minutes, a single core is on 100% on every vscode restart.
For file changes, esbonia builds only changed files as expected.

### Detailed steps

Open any folder with rst files and observe the debug console

### Extension information

184.0.0

### Visual Studio Code information

1.65.1

### Operating system information

Linux

### Python information

3.8.10

### Sphinx information

4.5.0

**Comment by alcarney** [comment]
The language server currently forces a full rebuild on startup, this is so the server can gather diagnostics for the whole project. Otherwise diagnostics would only be reported for the files Sphinx happened to touch during the incremental build.

However, I can see how that may be an issue for larger projects, so it's probably worth adding an option to the server to disable this.

**Comment by twodrops** [comment]
Thanks for that. Such an option would be very useful as the IDE is used not just by "documentation writers" but a lot of other developers who do not understand why VsCode appears slower suddenly.

**Comment by lextm** [comment]
Release 186.0.0 enables the new setting `esbonio.sphinx.forceFullBuild`.
