### ISSUE TITLE
[Feature request] Add outline support

### ISSUE THREAD

**Issue by rnixx** [vscode-restructuredtext/vscode-restructuredtext#57]
Hi,

it would be great if the document sections get shown in the outline view. This way there would be an overview about the document structure. By clicking a section in the outline the editor should jump to the related section then.

**Comment by kayhayen** [comment]
I have this on my WSL installation, but I am setting up devcontainers, and I do not have it there now, and I tried to google it how it working. I somehow suspect, this is solved, but I cannot tell how.

![grafik](https://github.com/vscode-restructuredtext/vscode-restructuredtext/assets/4226920/004c5eab-df35-46df-a3bc-59679b765ee6)

**Comment by kayhayen** [comment]
The syntax highlighting is an extension that the extension prompted me to install, it however doesn't work everywhere somehow, maybe it depends on tools or Python packages installed.

**Comment by lextm** [comment]
Close it, as the dependent syntax highlighting extension and esbonio extension each brings an implementation.

**Comment by kayhayen** [comment]
Something about esbonio is a mess, but I guess, this is not the correct place to ask it. When I try to install "esbonio" extension `swyddfa.esbonio` I think it complains from your extension, that it's incompatible version of esbonio, which I think that extension prompted to be allowed to install. As I am having this difficulty that my WSL has apparently proper esbonio installed, but my devcontainer does not, I am lost at figuring out how to get it. 

If you have any insights there, please let me know, otherwise just ignore me, I understand it is not your extension business maybe at all.

**Comment by lextm** [comment]
@kayhayen you need to use both prerelease versions of this extension and esbonion extension together to try out the latest features. The stable versions, however, were not compatible with each other.

New issues related to live preview/language services should be reported to https://github.com/swyddfa/esbonio/issues
