### ISSUE TITLE
Does Preview only work within a sphinx project?

### ISSUE THREAD

**Issue by gozzilli** [vscode-restructuredtext/vscode-restructuredtext#79]
## Question
Does Preview **only** work within a sphinx project? Does it not work for a standalone RestructuredText file? It doesn't seem to work without a ``conf.py`` file, but this is **not** clear from the README. 

### Extra Info
Please follow [the troubleshooting guide](https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/docs/sphinx.md#troubleshooting-guide) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: 49.0.0
- [ ] Visual Studio Code version: 1.19.3
- [ ] Operating System version: Mac OSX 10.13.2
- [ ] Python version: 3.6
- [ ] sphinx version: 1.6.3
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
Preview works on any .rst file

**Actual behavior**
Preview says "Unable to open "Preview ...": Error

**Detailed Steps to reproduce the problem**
Open Preview

**Comment by lextm** [comment]
No plan to support individual files at this moment.

**Comment by zwcloud** [comment]
@lextm 
> No plan to support individual files at this moment.

Then this should be point out clearly in the document. 😕  I had thought vscode-restructuredtext supports preview like markdown.

**Comment by lextm** [comment]
@zwcloud Markdown is a messy non-standard format, with confusing and misleading ecosystem, and all vendors have their flavors and extensions. I won't say much about VSCode built-in Markdown support, because its pros and cons are both obvious.

However, reStructuredText is more standardized around docutil and sphinx, as well as the Python ecosystem. That's why this extension was designed around sphinx and aims to generate the exact page for preview.

A recent pull request added rst2html based rendering engine, which solved this request of showing preview for "individual files". But its usage is rather limited.
